package com.mengzhihua.crm.service.service;
import com.mengzhihua.crm.common.*; import com.mengzhihua.crm.service.entity.*; import com.mengzhihua.crm.service.repository.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.time.format.*; import java.util.*;
@Service public class CaseService {
 private final CrmCaseRepository repo; private final CaseCommentRepository comments;
 public CaseService(CrmCaseRepository r,CaseCommentRepository c){repo=r;comments=c;}
 public PageResult<CrmCase> list(int page,int size,String keyword,Enums.CaseStatus status,Enums.CasePriority priority,Long accountId,Boolean overdue){List<CrmCase> all=repo.findAll();String k=keyword==null?"":keyword.toLowerCase();List<CrmCase> f=new ArrayList<>();for(CrmCase c:all){if(!k.isEmpty()&&!((c.getSubject()!=null&&c.getSubject().toLowerCase().contains(k))||(c.getCaseNo()!=null&&c.getCaseNo().toLowerCase().contains(k))))continue;if(status!=null&&c.getStatus()!=status)continue;if(priority!=null&&c.getPriority()!=priority)continue;if(accountId!=null&&!accountId.equals(c.getAccountId()))continue;if(Boolean.TRUE.equals(overdue)&&!(c.getSlaDueAt()!=null&&c.getSlaDueAt().isBefore(LocalDateTime.now())&&c.getStatus()!=Enums.CaseStatus.RESOLVED&&c.getStatus()!=Enums.CaseStatus.CLOSED))continue;f.add(c);}int from=Math.min((page-1)*size,f.size()),to=Math.min(from+size,f.size());return new PageResult<>(f.subList(from,to),f.size(),page,size);}
 public CrmCase get(Long id){return repo.findById(id).orElseThrow(()->new BizException("工单不存在"));}
 public CrmCase save(CrmCase c){if(c.getStatus()==null)c.setStatus(Enums.CaseStatus.NEW);if(c.getPriority()==null)c.setPriority(Enums.CasePriority.MEDIUM);if(c.getOrigin()==null)c.setOrigin(Enums.CaseOrigin.WEB);if(c.getType()==null)c.setType(Enums.CaseType.PROBLEM);if(c.getEscalated()==null)c.setEscalated(false);if(c.getCaseNo()==null)c.setCaseNo(nextNo());if(c.getSlaDueAt()==null)c.setSlaDueAt(LocalDateTime.now().plusHours(hours(c.getPriority())));return repo.save(c);}
 private long hours(Enums.CasePriority p){switch(p){case URGENT:return 4;case HIGH:return 8;case LOW:return 72;default:return 24;}}
 private String nextNo(){String prefix="CS"+LocalDate.now().format(DateTimeFormatter.BASIC_ISO_DATE);int n=(int)repo.count()+1;return prefix+String.format("%04d",n);}
 public void delete(Long id){repo.deleteById(id);}
 private boolean allowed(Enums.CaseStatus from,Enums.CaseStatus to){if(from==Enums.CaseStatus.CLOSED)return false;if(from==Enums.CaseStatus.NEW)return to==Enums.CaseStatus.IN_PROGRESS||to==Enums.CaseStatus.ESCALATED;if(from==Enums.CaseStatus.IN_PROGRESS)return to==Enums.CaseStatus.PENDING_CUSTOMER||to==Enums.CaseStatus.ESCALATED||to==Enums.CaseStatus.RESOLVED;if(from==Enums.CaseStatus.PENDING_CUSTOMER)return to==Enums.CaseStatus.IN_PROGRESS||to==Enums.CaseStatus.RESOLVED;if(from==Enums.CaseStatus.ESCALATED)return to==Enums.CaseStatus.IN_PROGRESS||to==Enums.CaseStatus.RESOLVED;return from==Enums.CaseStatus.RESOLVED&&(to==Enums.CaseStatus.CLOSED||to==Enums.CaseStatus.IN_PROGRESS);}
 public CrmCase status(Long id,Map<String,Object> b){CrmCase c=get(id);Enums.CaseStatus s=Enums.CaseStatus.valueOf(b.get("status").toString());if(!allowed(c.getStatus(),s))throw new BizException("非法的工单状态流转");if(s==Enums.CaseStatus.RESOLVED&&(b.get("solution")==null||b.get("solution").toString().trim().isEmpty()))throw new BizException("解决工单必须填写解决方案");c.setStatus(s);if(b.get("solution")!=null)c.setSolution(b.get("solution").toString());if(s==Enums.CaseStatus.RESOLVED)c.setResolvedAt(LocalDateTime.now());if(s==Enums.CaseStatus.CLOSED)c.setClosedAt(LocalDateTime.now());return repo.save(c);}
 public CrmCase escalate(Long id){CrmCase c=get(id);if(c.getStatus()==Enums.CaseStatus.CLOSED)throw new BizException("已关闭工单不能升级");c.setStatus(Enums.CaseStatus.ESCALATED);c.setEscalated(true);if(c.getPriority()==Enums.CasePriority.LOW)c.setPriority(Enums.CasePriority.MEDIUM);else if(c.getPriority()==Enums.CasePriority.MEDIUM)c.setPriority(Enums.CasePriority.HIGH);else if(c.getPriority()==Enums.CasePriority.HIGH)c.setPriority(Enums.CasePriority.URGENT);return repo.save(c);}
 public List<CaseComment> commentList(Long id){return comments.findByCaseIdOrderByCreatedAtAsc(id);}
 public CaseComment comment(Long id,CaseComment c){c.setId(null);c.setCaseId(id);return comments.save(c);}
}
