export const maps = {
  leadStatus: {
    NEW: "新建",
    CONTACTED: "已联系",
    QUALIFIED: "已确认",
    UNQUALIFIED: "不合格",
    CONVERTED: "已转化",
  },
  leadSource: {
    WEB: "网站",
    PHONE: "电话",
    REFERRAL: "转介绍",
    EVENT: "活动",
    PARTNER: "合作伙伴",
    OTHER: "其他",
  },
  stage: {
    QUALIFICATION: "资格审查",
    NEEDS_ANALYSIS: "需求分析",
    PROPOSAL: "方案报价",
    NEGOTIATION: "商务谈判",
    CLOSED_WON: "赢单",
    CLOSED_LOST: "丢单",
  },
  caseStatus: {
    NEW: "新建",
    IN_PROGRESS: "处理中",
    PENDING_CUSTOMER: "等待客户",
    ESCALATED: "已升级",
    RESOLVED: "已解决",
    CLOSED: "已关闭",
  },
  priority: {
    LOW: "低",
    MEDIUM: "中",
    HIGH: "高",
    URGENT: "紧急",
  },
  activityStatus: {
    PLANNED: "计划中",
    DONE: "已完成",
    CANCELLED: "已取消",
  },
  articleStatus: {
    DRAFT: "草稿",
    PUBLISHED: "已发布",
    ARCHIVED: "已归档",
  },
  quoteStatus: {
    DRAFT: "草稿",
    IN_REVIEW: "审批中",
    APPROVED: "已批准",
    REJECTED: "已驳回",
    ACCEPTED: "已接受",
    EXPIRED: "已过期",
  },
  approvalStatus: {
    PENDING: "待审批",
    APPROVED: "已通过",
    REJECTED: "已驳回",
  },
  role: {
    ADMIN: "管理员",
    SALES_MANAGER: "销售经理",
    SALES_REP: "销售代表",
    SERVICE_AGENT: "服务专员",
  },
  campaignType: {
    EMAIL: "邮件",
    EVENT: "活动",
    WEBINAR: "网络研讨会",
    ADS: "广告",
    REFERRAL: "转介绍",
    OTHER: "其他",
  },
  campaignStatus: {
    PLANNED: "计划中",
    IN_PROGRESS: "进行中",
    COMPLETED: "已完成",
    ABORTED: "已中止",
  },
  contractStatus: {
    DRAFT: "草稿",
    PENDING_SIGN: "待签署",
    ACTIVE: "生效中",
    EXPIRED: "已过期",
    TERMINATED: "已终止",
  },
  paymentStatus: {
    UNPAID: "未回款",
    PARTIAL: "部分回款",
    PAID: "已回款",
    OVERDUE: "已逾期",
  },
  paymentMethod: {
    BANK_TRANSFER: "银行转账",
    CASH: "现金",
    CHECK: "支票",
    ONLINE: "线上支付",
  },
};

export const colors = {
  NEW: "info",
  CONTACTED: "warning",
  QUALIFIED: "success",
  CONVERTED: "success",
  CLOSED_WON: "success",
  CLOSED_LOST: "danger",
  RESOLVED: "success",
  CLOSED: "info",
  URGENT: "danger",
  HIGH: "warning",
  MEDIUM: "",
  LOW: "info",
  DONE: "success",
  PUBLISHED: "success",
  DRAFT: "warning",
  IN_REVIEW: "warning",
  APPROVED: "success",
  REJECTED: "danger",
  ACCEPTED: "success",
  PENDING: "warning",
  ADMIN: "danger",
  SALES_MANAGER: "success",
  SALES_REP: "info",
  SERVICE_AGENT: "warning",
  IN_PROGRESS: "warning",
  COMPLETED: "success",
  ABORTED: "danger",
  PENDING_SIGN: "warning",
  ACTIVE: "success",
  EXPIRED: "info",
  TERMINATED: "danger",
  UNPAID: "info",
  PARTIAL: "warning",
  PAID: "success",
  OVERDUE: "danger",
};

export const text = (map, value) => map[value] || value || "-";
export const tagType = (value) => colors[value] || "";
